"""add student metric snapshots

Revision ID: b6f1918135ed
Revises: 712ebad8e3d1
Create Date: 2026-03-24 14:31:05.817113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f1918135ed'
down_revision: Union[str, Sequence[str], None] = '712ebad8e3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course_metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=False),
    sa.Column('brightspace_user_id', sa.Integer(), nullable=False),
    sa.Column('current_performance_pct', sa.Float(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('graded_items_count', sa.Integer(), nullable=False),
    sa.Column('total_items_count', sa.Integer(), nullable=False),
    sa.Column('not_submitted_weight_pct', sa.Float(), nullable=False),
    sa.Column('pending_submitted_weight_pct', sa.Float(), nullable=False),
    sa.Column('open_weight_pct', sa.Float(), nullable=False),
    sa.Column('overdue_count', sa.Integer(), nullable=False),
    sa.Column('pending_submitted_count', sa.Integer(), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_unit_id', 'brightspace_user_id', name='uq_student_course_metric_snapshot_course_user')
    )
    op.create_index(op.f('ix_student_course_metric_snapshots_brightspace_user_id'), 'student_course_metric_snapshots', ['brightspace_user_id'], unique=False)
    op.create_index(op.f('ix_student_course_metric_snapshots_org_unit_id'), 'student_course_metric_snapshots', ['org_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_course_metric_snapshots_org_unit_id'), table_name='student_course_metric_snapshots')
    op.drop_index(op.f('ix_student_course_metric_snapshots_brightspace_user_id'), table_name='student_course_metric_snapshots')
    op.drop_table('student_course_metric_snapshots')
    # ### end Alembic commands ###
